config/routes.rb
Guguplay::Application.routes.draw do
  devise_for :users
  resources :trips do
    resources :places
  end
  resources :places

  root 'welcome#index'

end

app/models/place.rb
class Place < ActiveRecord::Base
end

app/models/trip.rb
class Trip < ActiveRecord::Base
  has_many :trip_placeships
  has_many :places,:through=>:trip_placeships

end

app/models/trip_placeship.rb
class TripPlaceship < ActiveRecord::Base
belongs_to :trip
belongs_to :place
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController

  def new
    @place=Place.new
    find_trip
  end

  def create
    find_trip
    @place=Place.new(place_params)
    if @place.save
      add_place_to_trip @place,@trip
      redirect_to trip_path(@trip)
    else
      render :new
    end
  end

  private
  def find_place
    @place=Place.find(params[:id])
  end

  def find_trip
    @trip=Trip.find(params[:trip_id])
  end


  def place_params
    params.require(:place).permit(:name,:address)
  end

  def add_place_to_trip place,trip
    trip_placeship=TripPlaceship.new
    trip_placeship.place_id=place.id
    trip_placeship.trip_id=trip.id
    trip_placeship.save
  end

end

app/controllers/trips_controller.rb
class TripsController < ApplicationController
  def new
    @trip=Trip.new
  end
  def create
    @trip=Trip.new(trip_params)
    if @trip.save
      redirect_to trip_path(@trip)
    else
      render :new
    end
  end

  def show
    find_trip
@places=@trip.places
  end

  private
  def find_trip
    @trip=Trip.find(params[:id])
  end

  def trip_params
    params.require(:trip).permit(:name)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/helpers/trips_helper.rb
module TripsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>Guguplay</title>
	<%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
	<%= javascript_include_tag "application", "data-turbolinks-track" => true %>
	<%= csrf_meta_tags %>
</head>
<body>
	<%if current_user.present?%>  
	hello <%=current_user.email%>  
	<%= link_to('登出', destroy_user_session_path, :method => :delete) %>
	<%else%>
	<%= link_to "登入", new_user_session_path %>
	<%= link_to "註冊", new_user_registration_path %>
	<%end%>  
	<%= yield %>

</body>
</html>

app/views/places/new.html.erb
<div class="container">
	<div class="form-half">
	<%= form_for @place,:url=>trip_places_path(@trip),:html=>{:class=>'form-horizontal',:role=>'form'} do |f| %>
	<div class="form-group">
		<%=f.label :name, "place_name",:class=>'control-label'%>
		<%= f.text_field :name,:class=>'form-control'%>
	</div>

		<div class="form-group">
		<%=f.label :address, "place_address",:class=>'control-label'%>
		<%= f.text_field :address,:class=>'form-control'%>
	</div>

	<div class="pull-right">
		<%= link_to "取消", root_path,:class=>'btn btn-default' %>
		<%= f.submit "確定",:class=>"btn btn-success"%>
	</div>
	<% end %>
	<div class="warning-area">
		<%= render :partial => "common/form_error", :locals => { :table=>@place } %>
	</div>
	
</div>

</div>

app/views/trips/new.html.erb
<div class="container">
	<div class="form-half">
	<%= form_for @trip,:html=>{:class=>'form-horizontal',:role=>'form'} do |f| %>
	<div class="form-group">
		<%=f.label :name, "trip_name",:class=>'control-label'%>
		<%= f.text_field :name,:class=>'form-control'%>
	</div>

	<div class="pull-right">
		<%= link_to "取消", root_path,:class=>'btn btn-default' %>
		<%= f.submit "確定",:class=>"btn btn-success"%>
	</div>
	<% end %>
	<div class="warning-area">
		<%= render :partial => "common/form_error", :locals => { :table=>@trip } %>
	</div>
	
</div>

</div>

app/views/trips/show.html.erb
<div class="cotainer">
	<%=@trip.name%>  
	<%= link_to "add place", new_trip_place_path(@trip) %>
	<div>
	<h2>places</h2>

	</div>
</div>

app/views/welcome/index.html.erb
<div class="container">
<%= link_to "new_trip", new_trip_path,:class=>"btn btn-default" %>
</div>